[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.22"

# See more config options https://github.com/gakonst/foundry/tree/master/config

remappings = [
    '@openzeppelin=modified/openzeppelin',
    '@uniswap/v3-core=modified/uniswap/v3-core',
    '@uniswap/v3-periphery=modified/uniswap/v3-periphery',
    '@chainlink/=lib/chainlink-brownie-contracts/',
    'solmate/=lib/solmate/src/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]